plugins {
    alias(libs.plugins.android.application)
}


android {
    namespace 'com.example.eventify'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.eventify"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
        dataBinding true
    }
    
    packagingOptions {
        pickFirst '**/META-INF/notice.txt'
        pickFirst '**/META-INF/license.txt'
        pickFirst '**/META-INF/LICENSE.txt'
        pickFirst '**/META-INF/LICENSE'
        pickFirst '**/META-INF/NOTICE.txt'
        pickFirst '**/META-INF/NOTICE'
        pickFirst '**/META-INF/ASL2.0'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/INDEX.LIST'
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.navigation.runtime
    implementation libs.annotation
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.material.v1110alpha01
    implementation libs.retrofit
    implementation libs.logging.interceptor
    implementation libs.converter.gson
    implementation libs.shimmer
    implementation libs.material.v190
    implementation libs.recyclerview
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx
    implementation libs.databinding.runtime
    implementation libs.glide
    implementation libs.flexbox
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.9.0'
    implementation(platform("com.squareup.okhttp3:okhttp-bom:4.12.0"))
    implementation("com.squareup.okhttp3:okhttp")
    implementation("com.squareup.okhttp3:logging-interceptor")
    
    // WebSocket dependencies for chat
    implementation libs.java.websocket
    implementation libs.nv.websocket.client
//    implementation libs.spring.messaging

    implementation libs.swiperefreshlayout
    implementation libs.mpandroidchart

    // OpenStreetMap (osmdroid)
    implementation 'org.osmdroid:osmdroid-android:6.1.17'
    implementation 'org.osmdroid:osmdroid-wms:6.1.17'
    implementation 'org.osmdroid:osmdroid-mapsforge:6.1.17'
}
